nodeLinker: node-modules

npmRegistryServer: 'http://bscs.d3ata.com:8081/repository/npm-g'

unsafeHttpWhitelist:
  - 'bscs.d3ata.com'

yarnPath: .yarn/releases/yarn-sources.cjs

enableGlobalCache: true

enableImmutableInstalls: false
